project:
  type: website 
  output-dir: docs

website:
  title: "yanyuwu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cvyanyuwu.pdf
        text: CV
      
        
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

